# Generated by Django 5.2 on 2025-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estained_Payroll', '0002_alter_employeeprofile_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('none', 'None'), ('special-non-working', 'Special Non-Working Holiday'), ('local', 'Local Holiday'), ('national', 'National Holiday')], max_length=20)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
