# Generated by Django 5.2.1 on 2025-05-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estained_Payroll', '0003_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='payperiod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_id', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='LOANS',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='OTHERS',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='PHILHEALTH',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='SSS',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ActualAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_id', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('employee_id', models.CharField(max_length=20)),
                ('morning_in', models.CharField(blank=True, max_length=5, null=True)),
                ('morning_out', models.CharField(blank=True, max_length=5, null=True)),
                ('afternoon_in', models.CharField(blank=True, max_length=5, null=True)),
                ('afternoon_out', models.CharField(blank=True, max_length=5, null=True)),
                ('normal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'unique_together': {('payroll_id', 'date', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='audits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Action', models.CharField(max_length=40)),
                ('module', models.CharField(max_length=40)),
                ('section', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=40)),
                ('old_value', models.CharField(max_length=40)),
                ('New_Value', models.CharField(max_length=40)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estained_Payroll.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Filings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filing_Type', models.CharField(choices=[('none', 'None'), ('Overtime', 'Overtime'), ('Official Business', 'Official Business'), ('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave')], max_length=40)),
                ('Effective_Date', models.DateField()),
                ('Reason', models.CharField(max_length=40)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=40)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estained_Payroll.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_time_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='Estained_Payroll.employeeprofile')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estained_Payroll.payperiod')),
            ],
        ),
        migrations.CreateModel(
            name='stagingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('employee_id', models.CharField(max_length=20)),
                ('morning_in', models.CharField(blank=True, max_length=5, null=True)),
                ('morning_out', models.CharField(blank=True, max_length=5, null=True)),
                ('afternoon_in', models.CharField(blank=True, max_length=5, null=True)),
                ('afternoon_out', models.CharField(blank=True, max_length=5, null=True)),
                ('normal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'unique_together': {('payroll_id', 'date', 'employee_id')},
            },
        ),
    ]
